// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sqlserver.maid
{
    internal sealed partial class Vsix
    {
        public const string Id = "17e8fa63-4183-460e-8840-f8b2293f545c";
        public const string Name = "sqlserver-maid";
        public const string Description = @"Sqlserver Maid is a SQL Server Management Studio Add-in";
        public const string Language = "en-US";
        public const string Version = "1.0.3";
        public const string Author = "Duong Nguyen";
        public const string Tags = "ssms";
    }
}
