// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Sqlserver.maid
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidImagesString = "f5b57155-c84e-4bd1-812e-ed8512800bfd";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidSqlQueryEditorString = "b5a506eb-11be-4782-9a18-21265c2ca0b4";
        public static Guid guidSqlQueryEditor = new Guid(guidSqlQueryEditorString);

        public const string queryWindowContextCommandSetString = "33f13ac3-80bb-4ecb-85bc-225435603a5e";
        public static Guid queryWindowContextCommandSet = new Guid(queryWindowContextCommandSetString);

        public const string guidSqlMaidPackageString = "9dac5b5a-953b-456d-a667-2a1d20965229";
        public static Guid guidSqlMaidPackage = new Guid(guidSqlMaidPackageString);

        public const string guidCommandsString = "746c2fb4-20a2-4d26-b95d-f8db97c16875";
        public static Guid guidCommands = new Guid(guidCommandsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int queryWindowContextMenu = 0x0050;
        public const int PasteSpecialContextMenuGroup = 0x1020;
        public const int PasteAsCsvCommand = 0x0100;
        public const int JoinLinesCommand = 0x0101;
        public const int PasteAsInsertedCommand = 0x0102;
        public const int PasteAsInsertedWithHeaderCommand = 0x0103;
    }
}